FROM python:3.11-slim

WORKDIR /app

# Установка системных зависимостей
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Копирование зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование проекта
COPY . .

# Создание пользователя
RUN useradd -m -u 1001 consumer && chown -R consumer:consumer /app
USER consumer

CMD ["python", "manage.py", "run_kafka_consumer"]
