# Generated by Django 5.2.8 on 2025-12-14 19:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('internal_phone', models.IntegerField()),
                ('employee_count', models.IntegerField()),
                ('employee_phones', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'db_table': 'Department',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bandwidth', models.IntegerField()),
                ('setup_date', models.DateField()),
                ('port_count', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'Equipment',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('port', models.IntegerField()),
                ('hostname', models.CharField(max_length=255)),
                ('connection_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
                'db_table': 'Server',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Программное обеспечение',
                'verbose_name_plural': 'Программное обеспечение',
                'db_table': 'Software',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serial_number', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('inventory_number', models.IntegerField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='network_api.department')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
                'db_table': 'Computer',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HostComputer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_api.department')),
            ],
            options={
                'verbose_name': 'Хост-компьютер',
                'verbose_name_plural': 'Хост-компьютеры',
                'db_table': 'Host_Computer',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subnet_mask', models.GenericIPAddressField()),
                ('vlan', models.SmallIntegerField()),
                ('ip_range', models.CharField(max_length=100)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='network_api.equipment')),
            ],
            options={
                'verbose_name': 'Сеть',
                'verbose_name_plural': 'Сети',
                'db_table': 'Network',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NetworkComputer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('speed', models.IntegerField()),
                ('computer', models.ForeignKey(db_column='Computer_id', on_delete=django.db.models.deletion.CASCADE, to='network_api.computer')),
                ('network', models.ForeignKey(db_column='Network_id', on_delete=django.db.models.deletion.CASCADE, to='network_api.network')),
            ],
            options={
                'verbose_name': 'Сеть-Компьютер',
                'verbose_name_plural': 'Связи Сеть-Компьютер',
                'db_table': 'Network_Computer',
                'abstract': False,
                'managed': True,
                'unique_together': {('network', 'computer')},
            },
        ),
        migrations.AddField(
            model_name='network',
            name='computers',
            field=models.ManyToManyField(related_name='networks', through='network_api.NetworkComputer', to='network_api.computer'),
        ),
        migrations.CreateModel(
            name='ServerNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.ForeignKey(db_column='Network_id', on_delete=django.db.models.deletion.CASCADE, to='network_api.network')),
                ('server', models.ForeignKey(db_column='Server_id', on_delete=django.db.models.deletion.CASCADE, to='network_api.server')),
            ],
            options={
                'verbose_name': 'Сервер-Сеть',
                'verbose_name_plural': 'Связи Сервер-Сеть',
                'db_table': 'Server_Network',
                'abstract': False,
                'managed': True,
                'unique_together': {('server', 'network')},
            },
        ),
        migrations.AddField(
            model_name='server',
            name='networks',
            field=models.ManyToManyField(related_name='servers', through='network_api.ServerNetwork', to='network_api.network'),
        ),
        migrations.CreateModel(
            name='SoftwareComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.ForeignKey(db_column='Computer_id', on_delete=django.db.models.deletion.CASCADE, to='network_api.computer')),
                ('software', models.ForeignKey(db_column='Software_id', on_delete=django.db.models.deletion.CASCADE, to='network_api.software')),
            ],
            options={
                'verbose_name': 'ПО-Компьютер',
                'verbose_name_plural': 'Связи ПО-Компьютер',
                'db_table': 'Software_Computer',
                'abstract': False,
                'managed': True,
                'unique_together': {('software', 'computer')},
            },
        ),
        migrations.AddField(
            model_name='software',
            name='computers',
            field=models.ManyToManyField(related_name='software', through='network_api.SoftwareComputer', to='network_api.computer'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('position_id', models.BigIntegerField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='network_api.department')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'User',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.ForeignKey(db_column='Computer_id', on_delete=django.db.models.deletion.CASCADE, to='network_api.computer')),
                ('user', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='network_api.user')),
            ],
            options={
                'verbose_name': 'Пользователь-Компьютер',
                'verbose_name_plural': 'Связи Пользователь-Компьютер',
                'db_table': 'User_Computer',
                'abstract': False,
                'managed': True,
                'unique_together': {('user', 'computer')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='computers',
            field=models.ManyToManyField(related_name='users', through='network_api.UserComputer', to='network_api.computer'),
        ),
    ]
