# Generated by Django 5.2.8 on 2025-11-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('internal_phone', models.IntegerField()),
                ('employee_count', models.IntegerField()),
                ('employee_phones', models.JSONField()),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'db_table': '"LocalComputerNetwork"."Department"',
            },
        ),
    ]
