# Generated by Django 5.2.8 on 2026-02-12 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcomputer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_computers', to='network_api.department'),
        ),
    ]
